import product1 from "../src/assets/1.jpg";
import product3 from "../src/assets/2.jpg";
import product4 from "../src/assets/2.jpg";
import product5 from "../src/assets/3.jpg";
import product6 from "../src/assets/4.jpg";
import product7 from "../src/assets/5.jpg";
import product8 from "../src/assets/6.jpg";
import product9 from "../src/assets/7.jpg";
import product2 from "../src/assets/8.jpg";

export const Products = [
  {
    id: 1,
    type: "breakfast",
    image: product1,
    price: 10,
    name: "Eggs benedict",
    ingredients: [
      "baking powder ",
      "eggs ",
      "chopped chives ",
      "butter ",
      "milk ",
      "ham",
    ],
  },
  {
    id: 2,
    type: "Main",
    image: product2,
    name: "Lasagna",
    price: 10,
    ingredients: [
      "ground beef ",
      "pork sausage ",
      "tomato sauce ",
      "garlic cloves ",
      "sugar ",
      "salt ",
      "pepper ",
      "eggs ",
      "parsley ",
      "ricotta cheese ",
      "parmesan cheese ",
      "mozzarella cheese",
    ],
  },
  {
    id: 3,
    type: "Main",
    image: product3,
    price: 20,
    name: "Shrimp Scampi ",
    ingredients: [
      "shrimp ",
      "butter ",
      "olive oil ",
      "pepper ",
      "oregano ",
      "lemon juice ",
      "parmesan cheese ",
      "bread crumbs ",
      "parsley ",
      "pasta",
    ],
  },
  {
    id: 4,
    type: "Desserts",
    image: product4,
    price: 8,
    name: "Apple Pie",
    ingredients: [
      "apples ",
      "eggs ",
      "all-purpose flour ",
      "milk ",
      "white sugar ",
      "brown sugar ",
      "ginger ",
      "nutmeg ",
      "lemon juice",
    ],
  },
  {
    id: 5,
    type: "Main",
    image: product5,
    price: 15,
    name: "Kimchi Burgers",
    ingredients: [
      "chile sauce ",
      "mayonnaise ",
      "ketchup ",
      "bacon ",
      "ground beef ",
      "salt ",
      "American cheese ",
      " potato buns ",
      "cabbage",
    ],
  },
  {
    id: 6,
    type: "Main",
    image: product6,
    price: 10,
    name: "Spaghetti carbonara",
    ingredients: [
      "pancetta ",
      "pecorino cheese ",
      "parmesan ",
      "large eggs ",
      "spaghetti ",
      "garlic ",
      "butter ",
      "salt ",
      "black pepper",
    ],
  },
  {
    id: 7,
    type: "Main",
    image: product7,
    price: 15,
    name: "Quesadilla",
    ingredients: [
      "Sour cream ",
      "Mayonnaise ",
      "McCormick taco seasoning ",
      "McCormick chili powder ",
      "Tabasco green jalapeno sauce ",
      "Large burrito size flour tortillas ",
      "Boneless skinless chicken breasts ",
      "Vegetable oil ",
      "Shredded Monterey jack cheese ",
      "Shredded Cheddar cheese",
    ],
  },
  {
    id: 8,
    type: ["Desserts", "Breakfast"],
    image: product8,
    price: 8,
    name: "Fluffy Pancakes",
    ingredients: [
      "baking powder ",
      "eggs ",
      "all-purpose flour ",
      "sugar ",
      "milk",
      "white sugar ",
      "salt ",
      "butter",
    ],
  },
  {
    id: 9,
    type: "Desserts",
    image: product9,
    price: 8,
    name: "Hot Milk Cake",
    ingredients: [
      "baking powder ",
      "eggs ",
      "all-purpose flour ",
      "milk ",
      "butter ",
      "vanilla extract",
    ],
  },
];
